### ISSUE TITLE
USDT unable to deposit

### ISSUE THREAD

**Issue by brandoncomer** [umee-network/umee-v1-contracts#10]
USDT currentUTokenBalance does not come through, so we can't test depositing. It doesn't register any balance of USDT in our wallets, regardless of how much token we have.

Acceptance criteria: User should be able to deposit and borrow using USDT.

Here's the contract address for our test token: 0x4884E2a214DC5040f52A41c3f21c765283170B6e

**Comment by Hsiang-xxs** [comment]
No any transactions happened on uUSDT([0x4884E2a214DC5040f52A41c3f21c765283170B6e](url)), so no uUSDT minted to any addresses

**Comment by Hsiang-xxs** [comment]
U mean when u deposited USDT, there are no any uUSDTs returned to your wallet?

**Comment by brandoncomer** [comment]
No I can't even deposit. It's not registering the available balance in my wallet.

**Comment by brandoncomer** [comment]
Am able to deposit now.
