### ISSUE TITLE
Deposit APY and Borrow APY only updates for DAI

### ISSUE THREAD

**Issue by brandoncomer** [umee-network/umee-v1-contracts#11]
If you deposit any non-DAI asset, the deposit interest rate doesn't update. If you borrow any non-DAI asset, the borrow interest rate doesn't update as well. There's seems to be some difference in how DAI is handled versus other assets in the leverage contracts. 

Acceptance criteria: All asset interest rates should be appropriately updated when increasing or decreasing your deposits and borrow positions.

**Comment by brandoncomer** [comment]
We did find that USDC is updating, but the amount of increase is exponentially smaller than DAI when testing identical amounts of deposits and borrow positions.

**Comment by Hsiang-xxs** [comment]
Can pls share transaction hashes/links of:
- deposit and borrow DAI
- deposit and borrow USDC
- deposit and borrow any other assets

**Comment by brandoncomer** [comment]
@mmcconnell10 could you share the hashes/links for the transactions you completed per @Hsiang-xxs above?

**Comment by mmcconnell10** [comment]
@Hsiang-xxs 
[Deposit USDC](https://goerli.etherscan.io/tx/0xa27d5b20ccd6aa603138c2f81ba850f678a41ee604fb51f91ba9d53cfbf952ae)
[Deposit ATOM](https://goerli.etherscan.io/tx/0x8a28aa339c0c0c0eb3c0656f0e8d506f70e4022bf50f8e6c7cf8fada0bc8a621)
[Deposit DAI](https://goerli.etherscan.io/tx/0xa277bb9a4c7c01df14b58b2afbf921be78e6c9678e87bed35a18334095738135)
[Borrow USDC](https://goerli.etherscan.io/tx/0xe4edc477b2a5fd13f98a3c7fee115eb01a1e8faf03fe56bf9d4b6dba539cfb17)
[Withdraw DAI](https://goerli.etherscan.io/tx/0x7546d8efeef8fbf832bbf6ba25418de23499b80cacc9c1a4a5141f8c26185ec7)

**Comment by brandoncomer** [comment]
This looked like it was fixed, but is currently not showing up in the beta.umee.cc site. 
![Screen Shot 2021-12-14 at 2 08 27 PM](https://user-images.githubusercontent.com/90658712/146088861-65afc2b0-3891-4e3b-8709-5b226ef4cda5.png)
